server:
  port: 3003

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/eventflow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: redis
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info
